### ISSUE TITLE
Incorrect tags in appinspect/client.go?

### ISSUE THREAD

**Issue by firebus** [splunk/acs-privateapps-demo#14]
```
	var formdata url.Values
	if isVictoria {
		formdata = url.Values{
			"included_tags": []string{"cloud,self-service"},
		}
	} else {
		formdata = url.Values{
			"included_tags": []string{"private_app"},
		}
	}
```

IIRC private_app tag skips manual steps - it's what we'll use once APAV is available, but APAV is not yet available except in preview.
I think Classic is still using the cloud tag for appinspect.
If we want to support folks in Classic with APAV preview, maybe we need moar configuration options?

**Comment by kezialiman** [comment]
For classic, included tag is private app even before APAV is available due to the tag being hard-coded and doesn't take value from APAV flag. Fix for this is in, but nevertheless, tag will be "private_app". 

Closing this issue.
